# Required items.
game: "Far Cry 5"
api: 1
steamID: 552520
uid: com.thegreatcabbage.farcry5
author: TheGreatCabbage
packageName: farcry5
features:
  - graphics

# Optional items.
graphicsConfig: $!DOCUMENTS!$/My Games/Far Cry 5/gamerprofile.xml
gameDirectory: Far Cry 5
verificationPaths:
  - bin/FarCry5.exe